<div class='login-block'>
    <h4>WELCOME</h4>
    <?php
        //messages
        if ($this->messages) {
            foreach ($this->messages as $message) {
                echo "<p class='error-msg'>$message</p>";
            }
        }

        $form = $this->loginForm;
        $form->prepare();

        echo $this->form()->openTag($form);
        echo "<div class='row pull-left'>";
        echo $this->formRow($form->get('email'));
        echo "</div>";
        echo "<div class='row pull-left'>";
        echo $this->formRow($form->get('password'));
        echo "</div>";
        echo "<div class='row pull-left'>";
        echo $this->formRow($form->get('submit'));
        echo "</div>";
        echo $this->form()->closeTag($form);
    ?>
</div>