<?php
$highMediumLowText = array();

$highMediumLowText['Openness']['High'] = 'Your team scored high in the section of openness. For a team that works together over distance this is an achievement! To be able to continue being open and transparent to each other and facilitate new team members to adopt that openness as soon as possible, you can explore more activities and practices that foster openness within the team. ';
$highMediumLowText['Openness']['Medium'] = 'Your team scored medium in the section of openness. Increasing openness and transparency within your team will help you in communicating and collaborating effectively and will increase performance. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to work on being more open in the team. ';
$highMediumLowText['Openness']['Low'] = 'Your team scored low in the section of openness. Team members not contributing and holding back in voicing their opinions and ideas leads to sub-optimal decision making. This hampers the team in increasing performance. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to stimulate people opening up and contributing to the team.';

$highMediumLowText['Trust']['High'] = 'Your team has scored high in the section of trust. For a team that is collaborating virtually that is quite an achievement! Continue to engage with and support each other both personally and professionally and keep on exploring new (virtual) activities to keep your trust-levels up. You might want to use your expertise in this area to help other teams build up their trust.';
$highMediumLowText['Trust']['Medium'] = 'Your team has scored medium in the section of trust. Increasing the levels of trust within your global team will enable your team to improve communication, collaboration and productivity.  You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to help people become more comfortable with each other. ';
$highMediumLowText['Trust']['Low'] = 'Your team has scored low in the section of trust. Lack of trust causes people to be uncomfortable with each other and thus severely hampers a team in communicating and collaborating successfully. This issue needs to be addressed seriously. You can start by taking up the practices and activities mentioned in the “Practices and activities for improvement-section’ in the back of this report. ';

$highMediumLowText['Clarity']['High'] = 'Your team has scored high in the section of clarity. Having clarity on goals, behavioural values, roles and expected results set-up your team for success. To make sure your team stays aligned to the goals, make the goals, values and expected results explicitly visible for the team and regularly check if the team members are still on the same page with regard to goals, values, roles and results.';
$highMediumLowText['Clarity']['Medium'] = 'Your team has scored medium in the section of clarity, which indicates your global team needs to establish clear goals and behavioural values and align on a common way of work. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to establish more clarity on goals, values and practices within the global team. ';
$highMediumLowText['Clarity']['Low'] = 'Your team has scored low in the section of clarity, which indicates your global team is hampered by a lack of clarity on goals, behavioural values and a common way of work. To get tips on how to work on the necessary improvements, check the ‘Practices and activities for improvement-section’ in the back of this report.';

$highMediumLowText['Communication']['High'] = 'Your team has scored high in the section on communication. This indicates your team has the required agreements on communication, decision making and planning and follows through on them. To make sure your team stays aligned to the agreements, make them explicitly visible for the team and regularly check if the team members are still on the same page.';
$highMediumLowText['Communication']['Medium'] = 'Your team has scored medium in the section on communication. This indicates your team can improve on aligning on communication, decision making and planning and following through on them. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to create agreements on communication, decision making and planning within the global team.';
$highMediumLowText['Communication']['Low'] = 'Your team has scored low in the section on communication. This indicates your team is obstructed in reaching the teams objectives because communication, decision making and planning suffer from lack of alignment. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to create agreements on communication, decision making and planning within the global team.';

$highMediumLowText['Collaboration']['High'] = 'Your team has scored high in the section on collaboration. This indicates that your team members empathize with each other and they interact and communicate often. Team possess all the required skills and work together to create releasable increment. To sustain the high collaboration, team needs to be aligned to the business by regular and/or frequent interactions and communication.';
$highMediumLowText['Collaboration']['Medium'] = 'Your team has scored medium in the section on collaboration. This indicates that your team members are not really empowered to do the work in their own way and tends to lose working as a team and which makes it difficult to implement business requirements. Teams starts to lose the business knowledge and the expected results goes low.  You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to foster collaboration within the global team.';
$highMediumLowText['Collaboration']['Low'] = 'Your team has scored low in the section on collaboration. This indicates that your team is lacking opportunity to collaborate with each other and this make high impact on empiricism i.e. transparency, inspection and adaptation. For the teams lacking collaboration, gets rare chance to gain business knowledge and the interactions can be interpreted in wrong direction and result of which there is a high risk of disruption in team dynamics. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to foster collaboration within the global team.';

$highMediumLowText['Knowledge Sharing']['High'] = 'Your team has scored high in the section on knowledge sharing. This indicates that your team have all the required knowledge and skills to deliver a releasable increment and team possess high engagement level with POs and stakeholders. For the team to sustain cross functionality, team needs keep building the knowledge base with continuous engagement with POs and stakeholders.';
$highMediumLowText['Knowledge Sharing']['Medium'] = 'Your team has scored medium in the section on knowledge sharing. This indicates that your team members need to improve on gaining the business knowledge and needs to improve on communication and engagement with the Product Owner to understand the business. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to enhance business knowledge and sharing within the global team.';
$highMediumLowText['Knowledge Sharing']['Low'] = 'Your team has scored low in the section on knowledge sharing. This indicates that your team members have no or very low engagement with Product Owner and stakeholders and/or team is not in line with product vision. With low business knowledge, teams always face great challenges to deliver results what business expects. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to enhance business knowledge and sharing within the global team.';

$highMediumLowText['Motivation']['High'] = 'Your team has scored high in the section on motivation. This indicates that your team have highly motivated and self-driven team members. Teams with high motivation always hold shared ownership of the deliverables. Teams with higher motivation learns from their experience and make all important decisions as a team.';
$highMediumLowText['Motivation']['Medium'] = 'Your team has scored medium in the section on motivation. This indicates that your team members lack self-driven behaviour and have impact on the shared ownership on results. Teams lack motivation have high impact on team culture and values and this impact team deliverable and business. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to keep motivation high within the global team.';
$highMediumLowText['Motivation']['Low'] = 'Your team has scored medium in the section on motivation. This indicates that your team has no motivation and self-driven behaviour and team members are working with any sense and purpose. Teams with low motivation level don’t hold their team member accountable and team performance degrades. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to keep motivation high within the global team.';

$highMediumLowText['Improvement']['High'] = 'Your team has scored high in the section on improvement. This indicates that your team members have right mindset to continuously improve the way of work and the deliverables with a robust feedback cycle, and this brings the accountability within the teams to deliver business value.';
$highMediumLowText['Improvement']['Medium'] = 'Your team has scored medium in the section on improvement. This indicates that your team members are lacking the environment to improve continuously, and this create a high impact on accountability within the team towards team members and delivering business value. Team members who are reluctant to give and receive feedback and slow down the team’s performance. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to bring the feedback and improvement mindset within the global team.';
$highMediumLowText['Improvement']['Low'] = 'Your team has scored low in the section on improvement. This indicates that your team members are lacking feedback cycle and are not improving from the current state of doing the work and this bring monotonous behaviour within the team and that ends up building frustration and conflicts within the teams. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to bring the feedback and improvement mindset within the global team.';

$highMediumLowText['Innovation']['High'] = 'Your team has scored high in the section on innovation. This indicates that your team members are highly aligned to the business priorities and always thrive to innovate to deliver and simplify business needs. Team members are high on collaboration and always engage in result oriented communication. For the team to sustain high state, business must appreciate the ideas and empower the teams to explore, innovate and spread this energetic environment across the organization for better ways of delivering solutions.';
$highMediumLowText['Innovation']['Medium'] = 'Your team has scored medium in the section on innovation. This indicates that your team members are not self-organized and lack awareness of the impact of their work has on the organization. The team is reluctant to seek help and engage in result oriented communications thus not letting their creativity to innovate and find better ways of delivering solutions. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to enable teams to explore and innovate within the global team.';
$highMediumLowText['Innovation']['Low'] = 'Your team has scored low in the section on innovation. This indicates that your team members are not using their creativity and taking risk to explore and innovate better ways of delivering solution and hampered in reaching high performance and this impact business with longer time-to-market and losing competitive edge in the market. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to enable teams to explore and innovate within the global team.';

$highMediumLowText['Exploration']['High'] = 'Your team has scored high in the section on exploration. This indicates that your team members have open mindset to explore and find idea from outside sources and innovate them to deliver better solutions. Team members always engage themselves to explore better ways to deliver business solution. For the team to sustain high state, business must appreciate the ideas and empower the teams to explore & innovate better ways of delivering solutions.';
$highMediumLowText['Exploration']['Medium'] = 'Your team has scored medium in the section on exploration. This indicates that your team members are lacking alignment of their goals with business and not reluctant for taking risk to explore better ways of delivering solution and this may impact the business with average quality software or solutions and impact business on longer time-to-market. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to enable teams to explore and innovate within the global team.';
$highMediumLowText['Exploration']['Low'] = 'Your team has scored low in the section on exploration. This indicates that your team members are not inspired from outside sources and are not keen to explore better ways of working, team is not open to take high risk on improving from their current state and thus impact quality of the deliverables which has directly impact on business with longer time-to-market and losing competitive edge in the market. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to enable teams to explore and innovate within the global team.';

$highMediumLowText['Tooling']['High'] = 'Your global team has a high quality virtual work environment in place. Your tooling enables your team to communicate reliably and hold engaging, problem free virtual meetings. Keep on exploring new tooling to continue improving. Since many teams are struggling to find the right tooling and implementing it, you can consider spreading your knowledge and experience within your organization and beyond. ';
$highMediumLowText['Tooling']['Medium'] = 'Your global team has some challenges in working together optimally in a virtual set-up. Solving your tooling issues will enable your team to communicate reliably and hold problem free virtual meetings. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to solve the issues on technology.';
$highMediumLowText['Tooling']['Low'] = 'Your global team has severe challenges in working together virtually. Solving your tooling issues is essential to be able to communicate reliably and hold problem free virtual meetings. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to solve the issues on tooling.';

$highMediumLowText['Infrastructure']['High'] = 'Your global team scored high in this section. That means your team has solid infrastructure in place and is enabled to collaborate effectively and deliver the expected results. You might want to share your best practices with teams which are struggling getting their infrastructure right. ';
$highMediumLowText['Infrastructure']['Medium'] = 'Your global team scored medium in this section. This means that you have some challenges in getting your infrastructure to enable you to collaborate effectively and deliver the expected results. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to solve the issues on infrastructure.';
$highMediumLowText['Infrastructure']['Low'] = 'Your global team scored low in this section. The basic requirements for the team to work are insufficient if infrastructure is not in place and the team will not be able to collaborate effectively and deliver the expected results. It’s essential to improve in this area. You can check the ‘Practices and activities for improvement-section’ in the back of this report for tips on how to solve the issues on infrastructure. ';


?>

<?php
$strengthWeaknessSummary = $this->strengthWeaknessSummary;
$greenLevelThreshold = '3.75';
$yellowLevelThreshold = '3.25';

$html = '<br/>';
$html.='<h1>Detailed Summary</h1>';

$subCatAvg = array();
foreach($this->strengthWeaknessSummary as $category => $detailSubCategories){
    foreach($detailSubCategories as $detailSubCategory => $questions) {
        foreach ($questions as $qid => $qDetails) {
            $avg_rating = number_format($qDetails['total_rating'] / $qDetails['rating_count'], 2);
            $subCatAvg[$detailSubCategory]['total'][] = $avg_rating;
            $subCatAvg[$detailSubCategory]['category'] = $category;
            $subCatAvg[$detailSubCategory]['average'] = array_sum($subCatAvg[$detailSubCategory]['total'])/ count($subCatAvg[$detailSubCategory]['total']);
            $subCatAvg[$detailSubCategory]['qDetails'][] = $qDetails;

        }
    }
}


foreach ($subCatAvg as $subcategory => $subcategoryDetails) {
    $bgColor = ($subcategoryDetails['average'] >= $greenLevelThreshold) ? 'bgGreen' : (($subcategoryDetails['average'] >= $yellowLevelThreshold && $subcategoryDetails['average'] < $greenLevelThreshold) ? 'bgYellow': 'bgRed') ;
    $level = ($subcategoryDetails['average'] >= $greenLevelThreshold) ? 'High' : (($subcategoryDetails['average'] >= $yellowLevelThreshold && $subcategoryDetails['average'] < $greenLevelThreshold) ? 'Medium': 'Low') ;

    $html.= $this->partial('report-header.phtml');


    $html .= '<p class="pProgress">';
    $html .= '<label class="spnTitle">'. ucwords($subcategory).'</label>';
    $html .= '<label class="spnProgress '. $bgColor .'" style="width:'. ($subcategoryDetails['average'] * 80) .'px;">&nbsp;</label>';
    $html .= '<label>&nbsp;'. number_format($subcategoryDetails['average'], 2) .'</label>';
    $html .= '</p>';

    $html .= '<br/>
    <div class="divTable">
    <div class="divTableBody">
    <div class="divTableRow even">
    <div class="divTableCell"><strong>Fundamental</strong></div>
    <div class="divTableCell"><strong>Question</strong></div>
    <div class="divTableCell"><strong>Level</strong></div>
    <div class="divTableCell"><strong>Avg Score</strong></div>
    </div>
    ';
    $k = 0;
    foreach ($subcategoryDetails['qDetails'] as $qid => $qDetails) {
        if($k % 2 == 1) {
            $class = "even";

        } else {
            $class = 'odd';
        }

        $avg_rating = number_format($qDetails['total_rating'] / $qDetails['rating_count'], 2);
        //$subCatAvg[$detailSubCategory][] = $avg
        $html .= "<div class='divTableRow $class'>";
        $html .= '<div class="divTableCell"><div>' . ucfirst($subcategory) . '</div></div>';
        $html .= '<div class="divTableCell"><div>' . ucfirst($qDetails['question']) . '</div></div>';
        $html .= '<div class="divTableCell"><div>' . $subcategoryDetails['category'] . '</div></div>';
        $html .= '<div class="divTableCell" class="txtMiddle"><div>' . $avg_rating . '</div></div>';
        $html .= '</div>';
        $k++;
    }

    $html .= '</div></div>';
    $html .='<br/><br/><p>';
    $html .= $highMediumLowText[$subcategory][$level];
    $html .='</p>';


    $html .= '<div class="page-break"></div>';


}

echo $html;