<?php


$html = '
<p style="text-align: justify;">
<br/>


We experience that Technology is the basic condition that enable global teams to reach their potential of high performance:
<ul>
<li>Technology and tooling: State-of-the-art technology and tooling to create an optimal virtual work environment is the
fundament or the enabler.</li>
</ul>


<b>Level 1: Engaged Team</b><br/><br/>

The essential first step to take is to develop a sense of trust and safety in a global team. Only when people feel recognized and comfortable they will open up, show themselves and add value to the team. In global teams with high levels of trust people will be engaged in the work, contribute to (virtual) meetings, be open about their vulnerabilities and ask for help.

<br/><br/><b>Level 2: Aligned Team</b><br/><br/>

When sufficient time and energy is put into building a sense of trust and safety, a global team must align itself by creating clarity on goals, behaviours and optimal ways of communication over distance. The team needs to establish clarity on why a team exists, what is the connection between each team members personal goals and the teams goal, how members will behave, how the team will work together and who does what in the team. If done in an actionable way these answers can be used to setting guidelines for communication, decision making and planning.

<br/><br/><b>Level 3: Cross-Functional Team</b><br/><br/>

If a global team has alignment on goals, behaviours and roles, it can take the next step to become a cross-functional team. Cross-functionality increases collaboration and knowledge transfer between members of a global team. To be able to work together effectively, the team needs to develop a mindset and practices to share knowledge (both business and technical) on a regular basis.

<br/><br/><b>Level 4: Self-steering Team</b><br/><br/>

When a global team can depend on each team member to pick up the work of the team when needed, has a solid feedback cycle in place and transfers knowledge on technical and business level, the team is ready for the next step: developing into a self-steering team. In this stage a global team is able to hold each other accountable for behaviour and performance, shows discipline and takes full responsibility for and ownership of results. This increases motivation and purpose.

<br/><br/><b>Level 5: High Performing Team</b><br/><br/>

When a global team has become a self-steering unit, collectively responsible for the team performance, it is time to integrate the external focus also. The team is aware of the impact of its work has on the organization, uses its creativity, engages in communication outside their team, explores new ideas and fresh perspectives from outside sources, integrates these and innovates new products and/or services.

';

echo $html;