<?php

$html = '<p style="text-align: justify;">

<b><h1>Introduction</h1></b>
<br/>
This report shows the outcomes of the Global Team Health Assessment and will give a global team and
its leaders insight in its strengths and areas for improvement. The results of the assessment are data-driven
and quantitative, although the main purpose of the assessment is to give a qualitative perspective on the current
state of your global teams performance and to provide the team with insights to have a healthy discussion on
where and how to improve.
<br/><br/>
This report contains the following:
<br/><br/>
<ul>
<li>Explanation of the model
<li>Overview of the results
<li>Strenghts of the team
<li>Areas of improvement
<li>Individual differences
<li>Detailed results per level
<li>Practices and activities to stimulate improvement per level
</ul>

This report contains confidential information on a global teams performance and, although no team members
name is shown explicitly, should only be shared with people that are part of the team and its leaders.
Spreading it across further can only happen with each team members approval.
<br/><br/>

The first part of the report gives a general overview of the status of your teams health, while the second part gives you a detailed insight and suggestions to improve in the sections with lower score.


<b><h1>Explanation of the model</h1></b>

Building a successful team is hard. When a team consist of people from different cultures that work in different environments and time-zones it is even harder. At the same time, working in distributed or remote teams is a reality in a growing number of organizations in today’s global economy. The challenge organizations face is to build and maintain healthy global teams. We can help to solve this challenge.

<br/><br/>
Our global team model is based on a decade of hands-on experience in building and maintaining high performing Agile teams. Our teams work in a global set-up from our software laboratory in Bangalore, India with partner organizations in Netherlands and Germany. Over the years our coaches and experts have gathered many good practices that we want to share with the world. We have integrated these experiences with the intellectual capital of guru’s like Patrick Lencioni, Jim and Michelle McCarthy and recent research by Google and MIT in the field of high performance.

<br/><br/>
Combining our experience and research has resulted in a model for global team work, which the assessment is based on. The results shown in this report guide you in transforming your global team into a high performing unit where team members passionately add their maximum value to your organization.
</p>
';

echo $html;
