<div class="divReport">
    <a class="btnPrint linkButton" href="javascript:print();">Print</a>
    <?php
    $pageCount = 4;
    for ($i=1; $i<=4; $i++)
    {
        echo $this->partial('report-header.phtml');
        echo $this->partial("pages/page$i.phtml", array('team' => $this->team));
        echo $this->partial('report-footer.phtml');

        print '<div class="page-break"></div>';
    }
    ?>
</div>

<style>
    h3 {
        padding-top: 30px;
        padding-bottom: 20px;
        font-weight: bold;
    }
    h4 {
        padding: 15px 0px 10px 0px;
        font-weight: bold;
        font-size: 16px;
    }
    ul ul {
        padding-top: 15px;
    }
    li {
        text-decoration: none;
        padding-bottom: 10px;
    }
</style>
