<b>
    Practices and activities for improvement
</b>
<br>
<br>
<b>
    Prescriptions and advice to improve the health of your global team
</b>
<br><br>
<p>
<b>Technology</b><br><br>

Technology enables your global team to create an optimal virtual work environment and is the foundation of the Global Team Health Model.
With a solid technological fundament and tooling facilitates communication and collaboration over geographical distance, your team has
overcome the first hurdle in becoming a high performing global team. If your team needs to improve the foundation, here are some tips
and practices on how to do this.
    <br><br>
    <b>Tooling</b><br><br>
Start a research on the internet on what are the tools available to simulate an office online and start experimenting with the tools.
If there is low band with available or if there are many people participating from different places, Zoom is a very good video conferencing
tool (www.zoom.us). Sococo (www.sococo.com) is a virtual office tool and worthwhile exploring. If you want to increase the feeling of human
presence in a virtual meeting (especially useful if only one or two persons are joining virtually) you can consider using a telepresence
    robot (for instance www.kubi.com).<br><br>
    <b>Infrastructure</b><br><br>
To start with, get away from the legacy IT process, especially from the enterprise. While the Agile model accelerates the software
development process, many teams find that their IT environments are not optimized to support the full potential of their Agile development
release cycles. These legacy environments are often too slow, inflexible, and inadequate for Agile development processes.
    <br><br>

    <b>Engaged Team</b><br><br>

Fostering trust and openness amongst the members of a team is the first essential step to take when building a global team.
This encourages engagement and creates a sense of belonging and safety for people to contribute, open up, share and ask for help if needed.
    <br><br>
    <b>Trust</b><br><br>



    <b>Openness</b><br>


</p>