<?php
$result = $this->result;

print "<BR>";


$categories = array_keys($result);
echo "<table id='tblSummary'><th>";

        echo "<TD class='tblSummaryHeaders tblSummaryHeadersHorz'>Beginner</TD>";

    echo "<TD class='tblSummaryHeaders tblSummaryHeadersHorz'>Basic</TD>";

    echo "<TD class='tblSummaryHeaders tblSummaryHeadersHorz'>Intermediate</TD>";

    echo "<TD class='tblSummaryHeaders tblSummaryHeadersHorz'>Expert</TD>";

    echo "<TD class='tblSummaryHeaders tblSummaryHeadersHorz'>Champion</TD>";




    echo "</th>";

    $zeroScoreColor = "#ef174d";

    $fillcolor = array();
    $fillcolor[0] = "#ea4335";
    $fillcolor[1] = "#ea4335";
    $fillcolor[2] = "#fbbc05";
    $fillcolor[3] = "#e08128";
    $fillcolor[4] = "#34a853";
    $fillcolor[5] = "#34a853";

    $divident = 25;

    foreach ($categories as $k => $category) {
    echo "<tr>";


        $subCat = array_keys($result[$category]);

        $html = '';
        $catScore = 0; $catTotal = 0;
        for($i=0;$i<=4;$i++){
        if (isset($subCat[$i])) {
        $catScore = $catScore + $result[$category][$subCat[$i]]['rating'];
        $catTotal = $catTotal + $result[$category][$subCat[$i]]['total'];

        $percentage = ($result[$category][$subCat[$i]]['rating'] * 100) / $result[$category][$subCat[$i]]['total'];
        $key = ceil($percentage/$divident);
        $progressStyle = "background-size: " . $percentage . "% 100%; background-image: linear-gradient(to right, ". $fillcolor[$key] .", ". $fillcolor[$key] .");";
        $sliderStyle = "margin-left: ". (($percentage * 2) - 10) ."px";
        $zeroScoreStyle = "";
        if ($result[$category][$subCat[$i]]['rating'] == 0) {
        $zeroScoreStyle = "color:$zeroScoreColor;";
        }
        $html .=  "<TD>";
            $html .=  "<p>" . $subCat[$i] . "</p>";
            $html .= "<div class='divSubcatBg' style='". $progressStyle ."'>";
                $html .= "<div class='divSubcat'>";
                    $html .= "<div class='divScore'>";
                        $number = floor($result[$category][$subCat[$i]]['rating']) == $result[$category][$subCat[$i]]['rating'] ? floor($result[$category][$subCat[$i]]['rating']) : $result[$category][$subCat[$i]]['rating'];
                        $html .= "<span class='subcatScore' style='". $zeroScoreStyle ."'>" . $number . "</span>";
                        $html .= "<span class='subcatScoreCap'> /" . $result[$category][$subCat[$i]]['total'] . "</span>";
                        $html .= "</div>";
                    $html .= "</div>";
                $html .= "</div>";
            if ($percentage != 0 && $percentage != 100) {
            //$html .= "<span class='spnSlider' style='" . $sliderStyle . "'>|</span>";
            }
            $html .= "</TD>";
        } else {
        $html .= "<td>&nbsp;</td>";
        }
        }

        $percentage = ($catScore * 100) / $catTotal;
        $key = ceil($percentage/$divident);
        $rowHeight = 90;
        $divHeight = ($percentage*$rowHeight)/100;
        $marginTop = (100-$percentage) * $rowHeight / 100;
        $progressStyle = "height: ". $divHeight ."px; background-color: ". $fillcolor[$key] .";margin-top: ".$marginTop."px !important;";
        $sliderStyle = "margin-left: ". (($percentage * 2) - 10) ."px";
        $zeroScoreStyle = "";

        echo "<td class='tblSummaryHeaders tblSummaryHeadersVert'>";
            echo "<table class='tblCats'>";
                echo "<tr>";
                    echo "<td class='verticalProgress'>";
                        echo "<div class='divVerticalProgress'><div class='divVerticalProgressColor' style='". $progressStyle ."'>&nbsp;</div></div>";
                        echo "</td>";
                    echo "<td class='verticalContent'>";
                        echo "<p>" . $category . "</p>";
                        echo "<p class='pCatScore'>";
                            echo "<span class='subcatScore' style='". $zeroScoreStyle ."'>" . $catScore . "</span>";
                            echo "<span class='subcatScoreCap'> /" . $catTotal . "</span>";
                            echo "</p>";
                        echo "</td>";
                    echo "</tr>";
                echo "</table>";
            echo "</td>";
        echo $html;

        echo "</tr>";
    }


    echo "</table>";

?>


<style>
    #tblSummary {
        /*width: 60%;*/
        margin-top: 15px;
    }
    #tblSummary, #tblSummary td {
        border: 1px solid #cccccc;
    }
    #tblSummary td {
        padding: 5px;
    }
    #tblSummary th td {
        text-align: center !important;
    }
    #tblSummary tr {
        height: 80px; /* if row height is changed., vergical progress margin top calculation should chang */
    }
    #tblSummary td {
        width: 200px;
    }
    .tblSummaryHeaders {
        font-weight: bold;
        font-size: 14px;
    }
    .tblSummaryHeadersHorz, .tblSummaryHeadersVert {
        background-color: #e0e0e0;
    }
    .tblSummaryHeadersVert p {
        font-size: 12px !important;
    }
    td p {
        font-size: 11px !important;
        height: 40px !important;
    }
    #tblSummary .divSubcatBg {
        background-color: #e0e0e0;
        background-repeat: no-repeat;
    }
    #tblSummary .divSubcat {
        width: 100%;
        height: 22px;
        padding-top: 14px;
        padding-left: 5px;
        font-size: 10px;
    }
    #tblSummary .subcatScore {
        font-size: 22px;
    }
    #tblSummary .divScore {
        margin-top: -40px;
        text-align: right;
    }
    .spnSlider {
        padding: 6px 0px;
        border: 2px solid #2F323A;
        background-color: #2F323A;
        color: #eeeeee;
        border-radius: 3px;
        margin-top: -25px !important;
        position: absolute;
        z-index: 1;
    }
    .pCatScore {
        margin-top: -10px;
    }
    .tblCats {
        width: 100%;
    }
    .tblCats tr td {
        border: 0px !important;
        padding: 0px !important;
    }
    .verticalContent p {
        padding-left: 10px !important;
    }
    .verticalProgress {
        width: 8px !important;
        height: 90px;
        background-color: #e0e0e0;
    }
    .divVerticalProgress {
        width: 100% !important;
        height: 90px !important;
        display: table-cell;
        border: 1px solid #c8c8c8;
    }
    .divVerticalProgressColor {
        width: 8px;
    }
</style>