<?php

$html = "
<h3>Organization Background and Context</h3>
<p><u>Organization name</u> is a large, multinational <u>domain</u> organization with <u>service offerings</u> services:</p>
<p>
<u>list of services</u>
</p>
<h4>Business Context</h4>
<p>
This section provides the business and market context in which the DevOps adoption is being considered by <u>Organization name</u>.
</p>
<p>
<u>Define the the goals and constraints of the line(s) of business</u>
</p>
<h4>IT Context</h4>
<p>
This section provides the IT departments context in which the DevOps adoption is being considered by <Organization name>.
</p>
<p>
<u>Define the the goals and constraints of the IT department</u>
</p>
";

echo $html;