<?php

$html = "
<b><u>DevOps adoption recommendations</u></b>
    <br/><br/>
    DevOn recommended that the <u>Organization</u> <u>Line of Business</u> division adopt automation tools for each of the following four areas to address the inefficiencies that are causing waste and will eventually impact business.
    <br/><br/>
    <ul>
        <li>Implement a single collaboration tool that allows all stakeholders across the delivery life cycle to plan, collaborate, and share work items. This will address all collaboration issues by replacing the ticketing systems that are presently used.</li>
        <li>Adopt deployment automation that allows for the automated and reliable deployment of application components, as well as middleware code and configurations, to any environment in the delivery pipeline.</li>
        <li>Continue the adoption and rollout of test virtualization to provide the capability to carry out continuous testing of application components. Continuous testing at all stages of the delivery life cycle allows for the shifting left of testing, which results in early identification of defects and architectural flaws, and increases overall quality.</li>
        <li>
        Adopt a release management tool to provide capabilities to coordinate releases, resource availability, and environment availability. This ensures proper queuing of releases and their components as they flow through the delivery pipelines and integrate across their respective streams.
        <br/><br/>
        It is essential that the right processes be automated, and that they be optimized to achieve maximum efficiency. It is thus recommended by DevOn that the <u>Organization</u> <u>Line of Business</u> division work with subject matter experts (SMEs) to examine their existing processes in all four identified areas of automation and embark on a process improvement initiative across these areas. Introducing automation tools also provides the ability to explore alternate efficient processes that are not feasible when carried out manually.
        </li>
    </ul>
</li>
</ul>

<h4>Roadmap Adoption</h4>
<p>
Furthermore, in working with <u>Organization</u> management, prioritization of the recommendations in the roadmap was undertaken to allow them to decide which ones to address first. The investments required, and the expected return on investment for each, was a major consideration for the prioritization effort, as was the time to value needs for certain capabilities, defined by the lines of business goals and market timing needs.
</p>

";

echo $html;