<?php echo $this->doctype(); ?>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CDA : '. $this->translate('Continuous Delivery Assessment'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'stylesheet', 'type' => 'text/css', 'href' => 'https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,600italic,400italic')); ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('css/app.css'), 'screen,print')
            ->prependStylesheet($this->basePath('css/normalize.css'), 'screen,print')
            ->prependStylesheet($this->basePath('css/dataTables.jqueryUi.min.css'), 'screen,print')
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'), 'screen,print')
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'), 'screen,print')
            ->prependStylesheet($this->basePath('css/style.css'), 'screen,print')

        ; ?>
        <style>



        </style>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/radial-progress.js'))
            ->prependFile($this->basePath('js/what-input.min.js'))
            ->prependFile($this->basePath('js/dataTables.jqueryUi.min.js'))
            ->prependFile($this->basePath('js/jquery.dataTables.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <div class="hpta-container">
            <div class="menu">
                <a href="/" id="logo"><img src="/img/hpta.svg" alt="Logo GTHA"></a>
                <ul class="nav">
                    <?php if ($this->layout()->userAuthenticated) { ?>
                        <?php if ($this->layout()->userRole == \Application\Entity\Role::HPTA_ADMIN) { ?>
                            <li class="<?php if(strtolower($this->layout()->activePage) == 'question'){ echo 'active'; } ?> hpta-menu-item questions"><a href="<?php echo $this->url('question-add') ?>"><?php echo $this->translate('Questions') ?></a></li>
                            <li class="<?php if(strtolower($this->layout()->activePage) == 'company'){ echo 'active'; } ?> hpta-menu-item companies"><a href="<?php echo $this->url('company-add') ?>"><?php echo $this->translate('Companies') ?></a></li>
                        <?php } ?>
                        <?php if ($this->layout()->userRole == \Application\Entity\Role::COMPANY_ADMIN) { ?>
                            <li class="<?php if(strtolower($this->layout()->activePage) == 'team'){ echo 'active'; } ?> hpta-menu-item teams"><a href="<?php echo $this->url('team-add') ?>"><?php echo $this->translate('Teams') ?></a></li>
                            <li class="<?php if(strtolower($this->layout()->activePage) == 'teammember'){ echo 'active'; } ?> hpta-menu-item members"><a href="<?php echo $this->url('team-member-add') ?>"><?php echo $this->translate('Members') ?></a></li>
                        <?php } ?>
                        <?php if ($this->layout()->userRole == \Application\Entity\Role::TEAM_MEMBER) { ?>
                            <li class="<?php if(strtolower($this->layout()->activePage) == 'survey'){ echo 'active'; } ?> hpta-menu-item survey"><a href="javascript:void(0);"><?php echo $this->translate('Survey') ?></a>
                                <ul class="submenu">
                                <?php
                                echo "<li class='category'>";
                                echo "<a href='". $this->url('survey-take', array('subcategoryId' => 1)) ."'>Start Survey</a>";

                                echo '<ul class="category">';
                                foreach ($this->layout()->categories as $category => $categoryDetails) {
                                    $categoryClass = $categoryDetails['status'] ? ' survey-complete ' : ' survey-incomplete ';
                                    echo "<li class='categories'>";
                                    echo "<a href='javascript:void(0)' class='$categoryClass'>".ucfirst($category)."</a>";
                                    echo "<ul class='subcategories'>";
                                    foreach ($categoryDetails['subcategories'] as $id => $subcategory) {
                                        $subcategoryClass = $subcategory['status'] ? ' survey-complete ' : ' survey-incomplete ';
                                        echo "<li class='subcategory'><a href='". $this->url('survey-take', array('subcategoryId' => $id)) ."' class='$subcategoryClass'>". ucfirst($subcategory['name']) ."</a></li>";
                                    }
                                    echo "</ul>";
                                    echo "</li>";
                                }
                                echo '</ul>';

                                echo "</li>";

                                echo "<li class='category'>";
                                echo "<a href='".$this->url('survey-summary')."'>View Report</a>";
                                echo "</li>";
                                ?>
                                </ul>
                            </li>
                        <?php } ?>

                        <li class="hpta-menu-item logout"><a href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('Logout') ?></a></li>
                    <?php } ?>
                </ul>
            </div>
            <div class="sidebar">
                sidebar
            </div>
            <header class="header">
                <h2>CONTINUOUS DELIVERY ASSESSMENT</h2>
            </header>
            <?php if ($this->layout()->userAuthenticated) { ?>
                <span class="welcome-msg"><span class="welcome-icon"></span> <span class="welcome-user"><?php echo $this->user->getFullName(); ?></span></span>
            <?php } ?>
            <section class="content content-wrap">
                <?php
                    $messages = $this->flashMessenger()->getMessages();
                    foreach($messages as $message) {
                        echo "<p class='error-msg'>$message</p>";
                    }
                ?>
                <?php echo $this->content; ?>
            </section>
        </div>
    </body>
</html>