<div>
    <div>
        <?php
        //messages
        if ($this->messages) {
            foreach ($this->messages as $message) {
                echo "<p class='error-msg'>$message</p>";
            }
        }
        //add form
        $form = $this->teamAddForm;
        $form->prepare();

        echo $this->form()->openTag($form);
        echo "<div class='column pull-left'><label class='block' for='textName'>Team name</label>";
        echo $this->formRow($form->get('name'));
        echo "</div>";
        echo "<div class='column pull-left'><label class='block'>&nbsp;</label>";
        echo $this->formRow($form->get('submit'));
        echo "</div>";
        echo $this->form()->closeTag($form);
        ?>
    </div>
    <form method="post" action="<?php echo $this->url('team-compare'); ?>">
    <table id="tblList" class="tbl">
        <thead class="trHead">
        <tr>
            <th width="35%">Name</th>
            <th width="35%">Results</th>
        </tr>
        </thead>
        <tbody>
        <tr class="trItem"></tr>
        </tbody>
    </table>
        <input type="submit" value="Compare"> Select maximum of five teams please!
    </form>
</div>

<script>
    $(document).ready(function(){
        refreshList();
    });

    function refreshList()
    {
        $.ajax({
            url     : "<?php echo $this->url('team-list') ?>",
            dataType: "json",
            type    : "GET",
            success : function(data) {
                var i = 1;
                $('.trItem').remove();
                $.each(data, function(index, item){
                    var itemHtml = "<tr class='trItem'>";
                    itemHtml += "<td><input type=checkbox name=team[] value='"+item.id+"'> "+item.name+"</td>";
                    <?php $id = 1;?>
                    itemHtml += "<td>";
                    itemHtml += "<a target='_blank' href='<?php echo $this->url('survey-summary'); ?>/"+item.id+"'>View Result</a>  ";
                    //itemHtml += "<a target='_blank' href='<?php echo $this->url('survey-graph'); ?>/"+item.id+"'>View Graph</a> | ";
                    //itemHtml += "<a target='_blank' href='<?php echo $this->url('survey-tree'); ?>/"+item.id+"'>View Tree</a> | ";
                    //itemHtml += "<a target='_blank' href='<?php echo $this->url('generate-report'); ?>/"+item.id+"'>Generate Report</a>";
                    itemHtml += "</td>";

                    //itemHtml += "<td>";
                    //itemHtml += "<a class='linkUpdate' href='javascript:void(0)' qid='"+item.id+"' title='Edit'></a>";
                    //itemHtml += "<a class='linkDelete' href='javascript:void(0)' qid='"+item.id+"' title='Delete'></a>";
                    //itemHtml += "</td>";

                    itemHtml += "</tr>";
                    var newOption = $(itemHtml);
                    $('#tblList').append(newOption);
                    i++;
                });
                if (data.length <= 0) {
                    var newOption = $("<tr><td colspan='5'>No items found !</td></tr>");
                    $('#tblList').append(newOption);
                }
                initDeleteAction();
                initDataTable();
            }
        });
    }
    function initDeleteAction()
    {
        $('.linkDelete').click(function(){
            deleteItem($(this));
        });
    }
    function deleteItem(qObj)
    {
        $.ajax({
            url     : "<?php echo $this->url('team-delete') ?>",
            dataType: "json",
            type    : "POST",
            data    : "id="+ qObj.attr('qid'),
            success : function(status) {
                if (status) {
                    //refreshList();
                    $( location ).attr("href", "<?php echo $this->url('team-add') ?>");
                } else {
                    alert ("Error while deleting !");
                }
            }
        });
    }
    function initDataTable()
    {
        $('#tblList').dataTable({
            paginate : true,
            ordering : true,
            order : [],
            info : true,
            filter : true,
            retrieve : true
        });
    }
</script>